format = "$username$hostname$directory$git_branch$git_state$git_status$cmd_duration$line_break$python$conda$character"
right_format = "$direnv$shlvl"
[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](purple)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[conda]
format = "[\\(conda\\) $environment]($style) "
style = "bright-black"

[directory]
read_only = "  "
style = "blue"

[direnv]
allowed_msg = " "
disabled = false
format = "[$symbol$loaded$allowed]($style) "
loaded_msg = " "
not_allowed_msg = " "
style = "bold yellow"
symbol = "(direnv) "
unloaded_msg = " "

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "
style = "bright-black"

[git_status]
conflicted = ""
deleted = ""
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
modified = ""
renamed = ""
staged = ""
stashed = "≡"
style = "cyan"
untracked = ""

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[shlvl]
disabled = false
symbol = " "
threshold = 2
